-- MATEMÁTICAS
SELECT POWER(5, 2);
SELECT SQRT(25);
SELECT POWER(25, 0.5);
SELECT ROUND(5.99, 1);

-- TRUNCAR
SELECT TRUNCATE(5.99, 0);

-- DATA E HORA
SELECT CURRENT_DATE();
SELECT CURRENT_TIME();

-- HORA ATUAL DATA E HORA
SELECT NOW();
SELECT DAY(NOW());
SELECT MONTH(NOW());
SELECT YEAR(NOW());

-- CÁLCULO DE DIAS ENTRE DUAS DATAS
SELECT DATEDIFF('2024-05-28', NOW());

-- COMBINAÇÃO DE FUNÇÕES
SELECT TRUNCATE(DATEDIFF(NOW(), '1985-02-05') / 365, 0);

-- MANIPULAÇÃO DE STRING
SELECT REPEAT('*', 10);
SELECT REPLACE('casa', 'a', '@');
SELECT CONCAT('Programando', ' no MySQL');

-- MANIPULAÇÃO TAMANHO DE STRING
SELECT LOWER('Programando no MySQL');
SELECT UPPER('Programando no MySQL');
SELECT LENGTH(' MySQL ');

-- TRIM
SELECT LENGTH(TRIM(' MySQL '));
SELECT SUBSTRING('Programando no MySQL', 16, 5);